### PR TITLE
Griddedc march

### PR DESCRIPTION
**Pull request by gabe-parrish**
Hi Charles. Gridded C cold algorithm is done. 
We're still doing tests, i.e. generating ETf, but we're ready to move forward...

### CODE REVIEW

**Comment by gabe-parrish** [comment]
@cgmorton  - there still seems to be a bug using the new Daymet Tmax Image Collections, the .set() is not working?? for this commit we have the default set to DAYMET_MEDIAN_V2.

**Comment by cgmorton** [comment]
I'm pretty sure I just messed up setting the DOY property.  I'm trying to update it now.

**Review by cgmorton — CHANGES_REQUESTED** [review]
This all looks good to me except we should probably move the notebook file in the root folder to somewhere else.  Let me know if I can kick off some gridded Tcorr exports to test it out.

**Comment by macfriedrichs** [comment]
Thanks all, looks good to test out some exports now.

**Comment by gabe-parrish** [comment]
"(eeapi) C:\Users\gparrish\PycharmProjects\openet-ssebop-beta\tcorr_gridded>python tcorr_export_scene_by_date.py -i C:\Users\gparrish\PycharmProjects\openet-ssebop-beta\tcorr_gridded\ini\tcorr_daymet_v4_median_gridded.ini

Compute gridded Tcorr images by date

INI date range
  Start: 2016-01-01
  End:   2016-01-31

Initializing Earth Engine
Date: 2016-01-01
Date: 2016-01-02
LC08_021033_20160102
Traceback (most recent call last):
  File "tcorr_export_scene_by_date.py", line 862, in <module>
    main(ini_path=args.ini, overwrite_flag=args.overwrite,
  File "tcorr_export_scene_by_date.py", line 553, in main
    tcorr_img = t_obj.tcorr_gridded_cold
  File "C:\ProgramData\Anaconda3\envs\eeapi\lib\site-packages\openet\ssebop\image.py", line 29, in _lazy_property
    setattr(self, attr_name, fn(self))
  File "C:\ProgramData\Anaconda3\envs\eeapi\lib\site-packages\openet\ssebop\image.py", line 1579, in tcorr_gridded_cold
    tcorr_coarse_img = self.tcorr_image\
  File "C:\ProgramData\Anaconda3\envs\eeapi\lib\site-packages\openet\ssebop\image.py", line 29, in _lazy_property
    setattr(self, attr_name, fn(self))
  File "C:\ProgramData\Anaconda3\envs\eeapi\lib\site-packages\openet\ssebop\image.py", line 1172, in tcorr_image
    tmax = ee.Image(self.tmax)
  File "C:\ProgramData\Anaconda3\envs\eeapi\lib\site-packages\openet\ssebop\image.py", line 29, in _lazy_property
    setattr(self, attr_name, fn(self))
  File "C:\ProgramData\Anaconda3\envs\eeapi\lib\site-packages\openet\ssebop\image.py", line 870, in tmax
    raise ValueError('Unsupported tmax_source: {}\n'.format(
ValueError: Unsupported tmax_source: projects/earthengine-legacy/assets/projects/usgs-ssebop/tmax/daymet_v4_median_1980_2019"

**Comment by cgmorton** [comment]
Are you sure in installed the current version into your environment (i.e. `pip install . --no-deps` in the root folder)?

**Comment by gabe-parrish** [comment]
Absolutely forgot! Thanks for the reminder! :-)

**Pull request merged**
